# Project information's
sonar.projectKey=idmarinas_ui-bundle
sonar.organization=idmarinas
sonar.projectName=Ui Bundle
sonar.projectVersion=1.0.0
# Project URLs
sonar.links.homepage=https://github.com/idmarinas/ui-bundle
sonar.links.ci=https://github.com/idmarinas/ui-bundle/actions
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src/
sonar.tests=tests/
sonar.php.tests.reportPath=./build/reports/phpunit.xml
sonar.php.coverage.reportPaths=./build/reports/phpunit.coverage.xml
